version: "3.9"

services:
  backend:
    image: anusan2003/brightbuy-backend:latest
    env_file:
      - ./backend/.env
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    command: npm start
    networks:
      - brightbuy-network

  frontend:
    image: anusan2003/brightbuy-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - brightbuy-network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: brightbuy
      MYSQL_DATABASE: BrightBuy
    volumes:
      - mysql_data:/var/lib/mysql
      - ./seed.sql:/docker-entrypoint-initdb.d/01_seed.sql:ro
      - ./backend/sql/functions.sql:/docker-entrypoint-initdb.d/02_functions.sql:ro
      - ./backend/sql/procedures.sql:/docker-entrypoint-initdb.d/03_procedures.sql:ro
      - ./backend/sql/triggers.sql:/docker-entrypoint-initdb.d/04_triggers.sql:ro
      - ./backend/sql/indexes.sql:/docker-entrypoint-initdb.d/05_indexes.sql:ro
      - ./backend/sql/constraints.sql:/docker-entrypoint-initdb.d/06_constraints.sql:ro


    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pbrightbuy"]
      interval: 5s
      retries: 10
      start_period: 30s
    networks:
      - brightbuy-network

volumes:
  mysql_data:

networks:
  brightbuy-network:
    driver: bridge
