services:
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: brightbuy
      MYSQL_DATABASE: BrightBuy
    volumes:
      - mysql_data:/var/lib/mysql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pbrightbuy"]
      interval: 5s
      retries: 10
      start_period: 30s

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    ports:
      - "8081:8081"
    env_file:
      - ./backend/.env
    command: sh -c "npm ci --legacy-peer-deps && npm run dev"
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        # Rebuild image when Dockerfile or dependency manifests change
        - path: ./backend/Dockerfile
          action: rebuild
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild

  frontend:
    build:
      context: ./frontend
      target: builder
    container_name: frontend
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    ports:
      - "5173:5173"
    working_dir: /app
    command: sh -c "npm run dev -- --host"
    develop:
      watch:
        # Rebuild image when Dockerfile or dependency manifests change
        - path: ./frontend/Dockerfile
          action: rebuild
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild

volumes:
  mysql_data:
